generic-service:
  nameOverride: hmpps-accredited-programmes-manage-and-deliver-api
  productId: "HMPPS527" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-accredited-programmes-manage-and-deliver-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-accredited-programmes-manage-and-deliver-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=verify-full"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-accredited-programmes-manage-and-deliver-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

    rds-postgresql-instance-output:
      DB_HOST: "rds_instance_endpoint"
      DB_NAME: "database_name"
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-accredited-programmes-manage-and-deliver-api
