services:

  postgresql:
    image: postgres
    container_name: postgres
    networks:
      - hmpps
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=admin", "--dbname=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password

  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: hmpps-mandd-localstack-api
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  wiremock:
    image: wiremock/wiremock:3.13.0
    networks:
      - hmpps
    restart: always
    ports:
      - "9095:8080"
    volumes:
      - ./wiremock_mappings:/home/wiremock/mappings
    command: >
      --verbose

networks:
  hmpps:
