version: "3"
services:
  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: postgres-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin 
networks:
  hmpps: