info.app:
  name: HMPPS Accredited Programmes Manage And Deliver Api
  version: 1.0

spring:
  application:
    name: hmpps-accredited-programmes-manage-and-deliver-api

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${hmpps-auth.url}/.well-known/jwks.json
      client:
        registration:
          manage-and-deliver-api-client:
            provider: hmpps-auth
            client-id: hmpps-accredited-programmes-manage-and-deliver-ui-client-1
            client-secret: clientsecret
            authorization-grant-type: client_credentials
        provider:
          hmpps-auth:
            token-uri: ${hmpps-auth.url}/oauth/token

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    hikari:
      connectionTimeout: 1000
      validationTimeout: 500

  http:
    codec:
      max-in-memory-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

hmpps:
  sqs:
    reactiveApi: true
    queues:
      hmppsdomaineventsqueue:
        asyncQueueClient: true


max-response-in-memory-size-bytes: 750000

services:
  find-and-refer-intervention-api:
    base-url: http://localhost:9094
  ndelius-integration-api:
    base-url: http://localhost:9095
  oasys-api:
    base-url: http://localhost:9096