package uk.gov.justice.digital.hmpps.accreditedprogrammesmanageanddeliverapi.repository

import org.springframework.data.repository.Repository
import uk.gov.justice.digital.hmpps.accreditedprogrammesmanageanddeliverapi.entity.PreferredDeliveryLocationProbationDeliveryUnitEntity
import java.util.UUID

interface PreferredDeliveryLocationProbationDeliveryUnitRepository : Repository<PreferredDeliveryLocationProbationDeliveryUnitEntity, UUID>
