package uk.gov.justice.digital.hmpps.accreditedprogrammesmanageanddeliverapi.repository

import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository
import uk.gov.justice.digital.hmpps.accreditedprogrammesmanageanddeliverapi.entity.ReferralMotivationBackgroundAndNonAssociationsEntity
import java.util.UUID

@Repository
interface ReferralMotivationBackgroundAndNonAssociationsRepository : JpaRepository<ReferralMotivationBackgroundAndNonAssociationsEntity, UUID> {
  fun findByReferralId(referralId: UUID): ReferralMotivationBackgroundAndNonAssociationsEntity?
}
