-- For more information see /docs/schema-docs/2025-08-26-geographic-reference-data.md
INSERT INTO pdu (pdu_id, pdu_name, probation_region_id, ndelius_pdu_code) VALUES
    (1, 'East Kent', 'K', ''),
    (2, 'West Kent', 'K', ''),
    (3, 'Surrey', 'K', ''),
    (4, 'East Sussex', 'K', ''),
    (5, 'West Sussex', 'K', ''),
    (6, 'Essex North', 'I', ''),
    (7, 'Essex South', 'I', ''),
    (8, 'Suffolk', 'I', ''),
    (9, 'Norfolk', 'I', ''),
    (10, 'Hertfordshire', 'I', ''),
    (11, 'Northamptonshire', 'I', ''),
    (12, 'Bedfordshire', 'I', ''),
    (13, 'Cambridgeshire', 'I', ''),
    (14, 'Barnsley and Rotherham', 'C', ''),
    (15, 'Sheffield', 'C', ''),
    (16, 'Doncaster', 'C', ''),
    (17, 'Leeds', 'C', ''),
    (18, 'Wakefield', 'C', ''),
    (19, 'Kirklees', 'C', ''),
    (20, 'Bradford and Calderdale', 'C', ''),
    (21, 'York', 'C', ''),
    (22, 'North Yorkshire', 'C', ''),
    (23, 'Hull and East Riding', 'C', ''),
    (24, 'North and North East Lincolnshire', 'C', ''),
    (25, 'County Durham and Darlington', 'A', ''),
    (26, 'Gateshead and South Tyneside', 'A', ''),
    (27, 'Stockton and Hartlepool', 'A', ''),
    (28, 'Sunderland', 'A', ''),
    (29, 'Redcar, Cleveland and Middlesbrough', 'A', ''),
    (30, 'Newcastle Upon Tyne', 'A', ''),
    (31, 'North Tyneside and Northumberland', 'A', ''),
    (32, 'Salford', 'L', ''),
    (33, 'Manchester North', 'L', ''),
    (34, 'Manchester South', 'L', ''),
    (35, 'Bolton', 'L', ''),
    (36, 'Wigan', 'L', ''),
    (37, 'Bury and Rochdale', 'L', ''),
    (38, 'Stockport and Trafford', 'L', ''),
    (39, 'Tameside', 'L', ''),
    (40, 'Oldham', 'L', ''),
    (41, 'Cheshire West', 'B', ''),
    (42, 'Cheshire East', 'B', ''),
    (43, 'Warrington and Halton', 'B', ''),
    (44, 'Knowsley and St Helens', 'B', ''),
    (45, 'Sefton', 'B', ''),
    (46, 'Liverpool North', 'B', ''),
    (47, 'Liverpool South', 'B', ''),
    (48, 'Cumbria', 'B', ''),
    (49, 'Wirral', 'B', ''),
    (50, 'North West Lancashire', 'B', ''),
    (51, 'Blackburn', 'B', ''),
    (52, 'East Lancashire', 'B', ''),
    (53, 'Central Lancashire', 'B', ''),
    (54, 'Gloucestershire', 'G', ''),
    (55, 'Swindon and Wiltshire', 'G', ''),
    (56, 'Dorset', 'G', ''),
    (57, 'Bristol and South Gloucestershire', 'G', ''),
    (58, 'Plymouth', 'G', ''),
    (59, 'Cornwall and Isles of Scilly', 'G', ''),
    (60, 'Devon and Torbay', 'G', ''),
    (61, 'Somerset', 'G', ''),
    (62, 'Bath and North Somerset', 'G', ''),
    (63, 'Hampshire North and East', 'H', ''),
    (64, 'Southampton, Eastleigh and New Forest', 'H', ''),
    (65, 'Portsmouth and Isle of Wight', 'H', ''),
    (66, 'Oxfordshire', 'H', ''),
    (67, 'Buckinghamshire and Milton Keynes', 'H', ''),
    (68, 'East Berkshire', 'H', ''),
    (69, 'West Berkshire', 'H', ''),
    (70, 'Birmingham North, East and Solihull', 'E', ''),
    (71, 'Birmingham Central and South', 'E', ''),
    (72, 'Dudley and Sandwell', 'E', ''),
    (73, 'Walsall and Wolverhampton', 'E', ''),
    (74, 'Coventry', 'E', ''),
    (75, 'Warwickshire', 'E', ''),
    (76, 'Staffordshire and Stoke', 'E', ''),
    (77, 'Worcestershire', 'E', ''),
    (78, 'Herefordshire, Shropshire and Telford', 'E', ''),
    (79, 'Nottingham City', 'F', ''),
    (80, 'Nottinghamshire', 'F', ''),
    (81, 'Derby City', 'F', ''),
    (82, 'Derbyshire', 'F', ''),
    (83, 'Leicester, Leicestershire and Rutland', 'F', ''),
    (84, 'East and West Lincolnshire', 'F', ''),
    (85, 'Greenwich and Bexley', 'J', 'LDNBBG'),
    (86, 'Lewisham and Bromley', 'J', 'N07LEBR'),
    (87, 'Southwark', 'J', ''),
    (88, 'Lambeth', 'J', 'LDNLAW'),
    (89, 'Croydon', 'J', 'N07CROY'),
    (90, 'Kingston, Richmond and Hounslow', 'J', 'LDNHKR'),
    (91, 'Hammersmith, Fulham, Kensington, Chelsea and Westminster', 'J', 'LDNNHAK'),
    (92, 'Camden and Islington', 'J', 'LDNNCAI'),
    (93, 'Ealing and Hillingdon', 'J', 'LDNEHH'),
    (94, 'Wandsworth, Merton and Sutton', 'J', ''),
    (95, 'Brent', 'J', 'N07BRNT'),
    (96, 'Harrow and Barnet', 'J', 'LDNBEB'),
    (97, 'Hackney and City', 'J', 'LDNNHTH'),
    (98, 'Tower Hamlets', 'J', ''),
    (99, 'Enfield and Haringey', 'J', 'N07ENFH'),
    (100, 'Newham', 'J', 'N07NEWM'),
    (101, 'Redbridge and Waltham Forest', 'J', ''),
    (102, 'Barking, Dagenham and Havering', 'J', 'LDNBDN'),
    (103, 'North Wales', 'D', ''),
    (104, 'Gwent', 'D', ''),
    (105, 'Dyfed Powys', 'D', ''),
    (106, 'Cardiff and the Vale of Glamorgan', 'D', ''),
    (107, 'Swansea, Neath Port-Talbot', 'D', ''),
    (108, 'Cwm Taf Morgannwg', 'D', '')
